filebeat.inputs:
- type: filestream
  id: nginx-logs
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  fields:
    service: nginx
    type: nginx-access
  fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]
